version: '3.8'

services:
  # Spring Boot App Service
  app:
    image: inventory-management-system
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=1234
      - DB_NAME=inventory_management_database
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/inventory_management_database
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - db

  # PostgreSQL Database Service
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=inventory_management_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volume for database persistence
volumes:
  postgres_data:
